services:
  aptabase:
    container_name: aptabase
    image: ghcr.io/aptabase/aptabase:main
    restart: always
    depends_on:
      - aptabase-clickhouse
      - aptabase-postgres
    volumes:
      - ${APPDATA_DIR}/aptabase/config/secrets:/lostack_secrets
    environment:
      BASE_URL: https://aptabase.${DOMAINNAME}:8000
      DATABASE_URL: Server=aptabase-postgres;Port=5432;User Id=aptabase;Password=${DATABASE_PASSWORD};Database=aptabase
      CLICKHOUSE_URL: Host=aptabase-clickhouse;Port=8123;Username=aptabase;Password=${DATABASE_PASSWORD}
      TZ: ${TZ}
    entrypoint: |
      sh -c '
        if [ ! -f /lostack_secrets/auth.secret ]; then
          echo "Generating new AUTH_SECRET..."
          mkdir -p /lostack_secrets
          AUTH_SECRET=$(openssl rand -hex 32)
          echo "AUTH_SECRET=$$AUTH_SECRET" > /lostack_secrets/auth.secret
        else
          echo "Using existing AUTH_SECRET from /lostack_secrets/auth.secret"
        fi
        . /lostack_secrets/auth.secret
        export AUTH_SECRET
        dotnet Aptabase.dll
      '
    hostname: aptabase
    networks:
      - traefik_network
    labels:
      - homepage.description=App Analytics
      - homepage.group=Analytics
      - homepage.href=https://aptabase.${DOMAINNAME}/
      - homepage.icon=mdi-poll
      - homepage.name=Aptabase
      - lostack.default_duration=15m
      - lostack.autostart=true
      - lostack.group=aptabase
      - lostack.primary=true
      - lostack.details=Open source, privacy first and simple analytics for mobile and desktop apps.
      - lostack.tags=analytics,privacy
      - lostack.project_url=https://github.com/aptabase/aptabase
      - lostack.enable=true
      # - traefik.http.routers.aptabase.rule=Host(`aptabase.${DOMAINNAME}`)
      - lostack.port=8080
  aptabase-postgres:
    container_name: aptabase-postgres
    image: postgres:15-alpine
    restart: always
    volumes:
      - ${APPDATA_DIR}/aptabase/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: aptabase
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: ${TZ}
    hostname: aptabase-postgres
    networks:
      - traefik_network
    labels:
      - homepage.description=Aptabase Postgress
      - homepage.group=Databases
      - homepage.icon=postgres
      - homepage.name=Aptabase Postgres
      - lostack.autostart=true
      - lostack.group=aptabase
      - lostack.enable=true
  aptabase-clickhouse:
    container_name: aptabase-clickhouse
    image: clickhouse/clickhouse-server:23.8.4.69-alpine
    restart: always
    volumes:
      - ${APPDATA_DIR}/aptabase/events-db:/var/lib/clickhouse
    environment:
      CLICKHOUSE_USER: aptabase
      CLICKHOUSE_PASSWORD: ${DATABASE_PASSWORD}
      TZ: ${TZ}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    hostname: aptabase-clickhouse
    networks:
      - traefik_network
    labels:
      - homepage.description=Aptabase Clickhouse
      - homepage.group=Databases
      - homepage.icon=clickhouse
      - homepage.name=Aptabase Clickhouse
      - lostack.autostart=true
      - lostack.group=aptabase
      - lostack.enable=true