services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    hostname: portainer
    networks:
    - traefik_network
    labels:
    - homepage.description=Docker Manager
    - homepage.group=Admin
    - homepage.href=https://portainer.${DOMAINNAME}/
    - homepage.icon=portainer
    - homepage.name=Portainer
    - lostack.default_duration=15m
    - lostack.primary=true
    - lostack.tags=docker,managment,tools
    - lostack.project_url=https://github.com/portainer/portainer
    - lostack.details=Portainer Community Edition is a lightweight service delivery platform for containerized applications that can be used to manage Docker, Swarm, Kubernetes and ACI environments. It is designed to be as simple to deploy as it is to use. The application allows you to manage all your orchestrator resources (containers, images, volumes, networks and more) through a ‘smart’ GUI and/or an extensive API.\n\nPortainer consists of a single container that can run on any cluster. It can be deployed as a Linux container or a Windows native container.
    - lostack.autostart=true
    - lostack.group=portainer
    - lostack.enable=true
    # - traefik.http.routers.portainer.rule=Host(`portainer.${DOMAINNAME}`)
    - lostack.port=9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${APPDATA_DIR}/portainer:/data
