services:
  pingvin-share:
    image: stonith404/pingvin-share
    restart: unless-stopped
    container_name: pingvin-share
    hostname: pingvin-share
    networks:
    - traefik_network
    labels:
    - homepage.description=Beautiful File Sharing
    - homepage.group=File Transfer
    - homepage.href=https://pingvin-share.${DOMAINNAME}/
    - homepage.icon=pingvin-share
    - homepage.name=Pingvin Share
    - lostack.default_duration=15m
    - lostack.primary=true
    - lostack.tags=files,sharing,notes
    - lostack.project_url=https://github.com/stonith404/pingvin-share
    - lostack.details=A self-hosted file sharing platform that combines lightness and beauty, perfect for seamless and efficient file sharing.
    - lostack.autostart=true
    - lostack.group=pingvin-share
    - lostack.enable=true
    # - traefik.http.routers.pingvin-share.rule=Host(`pingvin-share.${DOMAINNAME}`)
    - lostack.port=3000
    volumes:
    - ${APPDATA_DIR}/pingvin-share:/opt/app/backend/data
    - ${MEDIA_DIR}/images:/opt/app/frontend/public/img
