services:
  metatube:
    container_name: metatube
    restart: always
    image: jvt038/metatube:latest
    environment:
    - PORT=5000
    - HOST=0.0.0.0
    hostname: metatube
    networks:
    - traefik_network
    labels:
    - 'homepage.description=Image Hosting '
    - homepage.group=Video Downloaders
    - homepage.href=https://metatube.${DOMAINNAME}/
    - homepage.icon=mdi-play
    - homepage.name=Metatube
    - lostack.default_duration=15m
    - lostack.primary=true
    - lostack.tags=videos,downloader,files
    - lostack.project_url=https://github.com/JVT038/MetaTube
    - lostack.details=MetaTube downloads video from YouTube and can add metadata from a specified metadata provider on the downloaded file.
    - lostack.autostart=true
    - lostack.group=metatube
    - lostack.enable=true
    # - traefik.http.routers.metatube.rule=Host(`metatube.${DOMAINNAME}`)
    - lostack.port=5000
    volumes:
    - ${MEDIA_DIR}/downloads/youtube:/downloads:rw
    - ${APPDATA_DIR}/metatube/database:/database:rw
    - ${APPDATA_DIR}/metatube/migrations:/config/migrations:rw'
