services:
  twip:
    image: rouhim/this-week-in-past
    environment:
      SLIDESHOW_INTERVAL: 10
    restart: unless-stopped
    container_name: twip
    hostname: twip
    networks:
    - traefik_network
    labels:
    - homepage.description=Image Slideshow
    - homepage.group=Media
    - homepage.href=https://twip.${DOMAINNAME}/
    - homepage.icon=mdi-image
    - homepage.name=Twip
    - lostack.default_duration=15m
    - lostack.primary=true
    - lostack.tags=server,api,proxy
    - lostack.project_url=https://github.com/twip/twip
    - lostack.details=Twitter API proxy in PHP
    - lostack.autostart=true
    - lostack.group=twip
    - lostack.enable=true
    # - traefik.http.routers.twip.rule=Host(`twip.${DOMAINNAME}`)
    - lostack.port=8080
    volumes:
    - ${MEDIA_DIR}/images:/resources:ro
