services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    hostname: code-server
    restart: always
    networks:
    - traefik_network
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
      DEFAULT_WORKSPACE: ${CODE_SERVER_WORKSPACE}
      PASSWORD: ${ADMIN_PASSWORD}
      SUDO_PASSWORD: ${SUDO_PASSWORD}
      PROXY_DOMAIN: code-server.${DOMAINNAME}
    ports:
    - ${CODE_SERVER_PORT}:8443
    volumes:
    - ${APPDATA_DIR}/code-server:/config
    - ./:/workspace:rw
    labels:
    - traefik.enable=true
    - traefik.http.routers.code-server.entrypoints=https
    - traefik.http.routers.code-server.rule=Host(`code-server.${DOMAINNAME}`)
    - traefik.http.services.code-server.loadbalancer.server.port=8443
    - homepage.name=Code Server
    - homepage.group=Development
    - homepage.icon=vscode
    - homepage.description=Local File Editor
    - homepage.href=https://code-server.${DOMAINNAME}/
    - sablier.enable=true
    - sablier.group=code-server
    - lostack.duration=2h
    - lostack.primary=true
