services:
  nginx-serve:
    image: nginx:latest
    container_name: nginx-serve
    hostname: nginx-serve
    restart: unless-stopped
    environment:
      AUTO_INDEX: on
      TZ: ${TZ}
    entrypoint: |
      /bin/sh -c "
      echo 'events {}' > /etc/nginx/nginx.conf && \
      echo 'http {
        server {
          listen 80;
          location / {
            root /usr/share/nginx/html;
            autoindex on;
          }
        }
      }' >> /etc/nginx/nginx.conf && \ nginx -g 'daemon off;' "
    volumes:
      - ${MEDIA_DIR}/www:/usr/share/nginx/html/
    networks:
      - traefik_network
    labels:
      - homepage.description=Nginx Fileserver
      - homepage.group=File Transfer
      - homepage.href=https://nginx-serve.${DOMAINNAME}/
      - homepage.icon=nginx
      - homepage.name=Nginx Serve
      - lostack.autostart=true
      - lostack.group=nginx-serve
      - lostack.enable=true
      # - traefik.http.routers.nginx-serve.rule=Host(`nginx-serve.${DOMAINNAME}`)
      - lostack.port=80
      - lostack.default_duration=15m
      - lostack.primary=true
      - lostack.tags=lostack
      - lostack.login=userless
      - lostack.tags=files,server,http,https
      - lostack.project_url=https://github.com/AndrewSpangler/LoStack
      - lostack.details=LoStack Custom Package - Easily serve files in ${MEDIA_DIR}/www. Nginx with a built-in entrypoint script to configure it to serve files in a directory.