services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    hostname: code-server
    restart: always
    networks:
      - traefik_network
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
      DEFAULT_WORKSPACE: /workspace
      PASSWORD: ${ADMIN_PASSWORD}
      SUDO_PASSWORD: ${ADMIN_PASSWORD}
      PROXY_DOMAIN: code-server.${DOMAINNAME}
    volumes:
      - ${APPDATA_DIR}/code-server:/config
      - ./:/workspace:rw
    labels:
      - "homepage.name=Code Server"
      - "homepage.group=Development"
      - "homepage.icon=vscode"
      - "homepage.description=File Editor"
      - "homepage.href=https://code-server.${DOMAINNAME}/"
      - "homepage.description=VS Code in the browser"
      - "lostack.enable=true"
      - "lostack.autostart=true"
      - "lostack.group=code-server"
      - "lostack.duration=4h"
      - "lostack.primary=true"
      - "lostack.port=8443"
      - lostack.default_duration=4h
      - lostack.project_url=https://github.com/coder/code-server
      - "lostack.details=VS Code in the browser"
      - lostack.tags=administration,editor,files
