services:
  ackee:
    image: electerious/ackee
    container_name: ackee
    hostname: ackee
    networks:
     - traefik_network
    environment:
      - WAIT_HOSTS=ackee-mongo:27017
      - ACKEE_MONGODB=mongodb://ackee-mongo:27017/ackee
      - ACKEE_USERNAME=${LDAP_ADMIN_USERNAME}
      - ACKEE_PASSWORD=${ADMIN_PASSWORD}
      - ACKEE_TTL=3600000
      - ACKEE_ALLOW_ORIGIN=https://ackee.${DOMAINNAME}
    depends_on:
      - ackee-mongo
    restart: always  
    labels:
      - "lostack.enable=true"
      - lostack.port=3000
      - "homepage.name=Ackee"
      - "homepage.group=Apps"
      - "homepage.icon=mdi-google-analytics"
      - "homepage.description=Analytics Tool"
      - "homepage.href=https://ackee.${DOMAINNAME}/"
      - lostack.autostart=true
      - lostack.group=ackee
      - lostack.default_duration=15m
      - lostack.primary=true
      - "lostack.details=Self-hosted, Node.js based analytics tool for those who care about privacy."
      - lostack.tags=analytics,privacy,api,graphql
      - lostack.project_url=https://github.com/electerious/Ackee

  ackee-mongo:
    image: mongo
    container_name: ackee-mongo
    hostname: ackee-mongo
    networks:
     - traefik_network
    volumes:
      - ${APPDATA_DIR}/ackee/db:/data/db
    labels:
      - "homepage.name=Ackee MongoDB"
      - "homepage.group=Databases"
      - "homepage.icon=mongodb"
      - "homepage.description=Ackee Database"
      - "lostack.autostart=true"
      - "lostack.group=ackee"
      - "lostack.enable=true"