services:
  gitea:
    image: docker.gitea.com/gitea:nightly
    container_name: gitea
    environment:
    - USER_UID=1000
    - USER_GID=1000
    - GITEA__database__DB_TYPE=mysql
    - GITEA__database__HOST=gitea-db:3306
    - GITEA__database__NAME=gitea
    - GITEA__database__USER=gitea
    - GITEA__database__PASSWD=${DATABASE_PASSWORD}
    - GITEA__database__CHARSET=utf8mb4
    - GITEA__server__DOMAIN=${DOMAINNAME}
    - GITEA__server__ROOT_URL=https://gitea.${DOMAINNAME}
    - GITEA__server__HTTP_PORT=3000
    - GITEA__server__SSH_PORT=22
    - GITEA__security__SECRET_KEY=${GITEA_SECRET_KEY}
    - GITEA__security__INTERNAL_TOKEN=${GITEA_INTERNAL_TOKEN}
    - GITEA__service__DISABLE_REGISTRATION=true
    - GITEA__service__ALLOW_ONLY_EXTERNAL_REGISTRATION=true
    - GITEA__service__SHOW_REGISTRATION_BUTTON=false
    - GITEA__service__REQUIRE_SIGNIN_VIEW=true
    - GITEA__auth__LDAP_AUTH_SOURCE_NAME=OpenLDAP
    - GITEA__auth__LDAP_SECURITY_PROTOCOL=unencrypted
    - GITEA__auth__LDAP_HOST=openldap
    - GITEA__auth__LDAP_PORT=${OPENLDAP_PORT}
    - GITEA__auth__LDAP_USER_SEARCH_BASE=${LDAP_BASE_DN}
    - GITEA__auth__LDAP_USER_FILTER=(&(objectClass=inetOrgPerson)(uid=%s))
    - GITEA__auth__LDAP_ADMIN_FILTER=(memberOf=cn=admins,ou=groups,${LDAP_BASE_DN})
    - GITEA__auth__LDAP_USERNAME_ATTRIBUTE=uid
    - GITEA__auth__LDAP_FIRSTNAME_ATTRIBUTE=givenName
    - GITEA__auth__LDAP_SURNAME_ATTRIBUTE=sn
    - GITEA__auth__LDAP_EMAIL_ATTRIBUTE=mail
    - GITEA__auth__LDAP_BIND_DN=cn=${LDAP_READONLY_USER_USERNAME},${LDAP_BASE_DN}
    - GITEA__auth__LDAP_BIND_PASSWORD=${LDAP_READONLY_USER_PASSWORD}
    - GITEA__auth__LDAP_USER_DN_TEMPLATE=uid=%s,ou=people,${LDAP_BASE_DN}
    - GITEA__auth__LDAP_SYNC_USER_ATTRS=true
    - GITEA__auth__LDAP_ATTRIBUTES_IN_BIND=false
    - GITEA__auth__LDAP_USE_PAGED_SEARCH=true
    - GITEA__auth__LDAP_SEARCH_PAGE_SIZE=250
    - GITEA__cron.sync_external_users__ENABLED=true
    - GITEA__cron.sync_external_users__RUN_AT_START=true
    - GITEA__cron.sync_external_users__SCHEDULE=@every 24h
    restart: always
    networks:
    - traefik_network
    depends_on:
    - gitea-db
    volumes:
    - ${APPDATA_DIR}/gitea:/data
    labels:
    - lostack.enable=true
    # - traefik.http.routers.gitea.rule=Host(`gitea.${DOMAINNAME}`)
    - traefik.http.routers.gitea.tls=true
    - lostack.port=3000
    - homepage.name=Gitea
    - homepage.group=Development
    - homepage.icon=gitea
    - homepage.description=Git Repository Management
    - homepage.href=https://gitea.${DOMAINNAME}/
    - lostack.autostart=true
    - lostack.group=gitea
    - lostack.default_duration=15m
    - lostack.primary=true
    - lostack.tags=git,files,server,ldap
    - lostack.project_url=https://github.com/go-gitea/gitea
    - lostack.details=Git with a cup of tea! Painless self-hosted all-in-one software development service, including Git hosting, code review, team collaboration, package registry and CI/CD
  gitea-db:
    image: mariadb:10.11
    container_name: gitea-db
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    - MYSQL_USER=gitea
    - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    - MYSQL_DATABASE=gitea
    - MYSQL_CHARSET=utf8mb4
    - MYSQL_COLLATION=utf8mb4_unicode_ci
    networks:
    - traefik_network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      --innodb-large-prefix=ON --innodb-file-format=Barracuda --innodb-file-per-table=ON
    volumes:
    - ${APPDATA_DIR}/gitea-db:/var/lib/mysql
    labels:
    - homepage.name=Gitea MariaDB
    - homepage.group=Databases
    - homepage.icon=mariadb
    - homepage.description=Gitea DB
    - homepage.href=https://gitea.${DOMAINNAME}/
    - lostack.autostart=true
    - lostack.group=gitea
    - lostack.enable=true
